baseurl									= "https://www.pierremorsa.com/"
title										= "Pierre Morsa"
defaultContentLanguage		= "fr"
language									= "fr"
languageCode							= "fr"
languageName							= "Français"
paginate								= 5


[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
   		unsafe						= true	# added to allow raw HTML in page .Content


[taxonomies]
	category	= "categories"
	company		= "companies"
	promised	= "promised"
	deadline		= "deadline"

[params]
  # Meta tag description
  description						= "Le blog de Pierre Morsa, où il partage ses réflexions de comptoir. Co-fondateur et Creative Cat d'Ideas on Stage, agence spécialisée dans les présentations en public."

	# Sections whose pages are listed
	mainSections 					= ["post"]

	# Avatar picture on top of site
	[params.avatar]
	  src       					= "/pictures/main/pierre-morsa-avatar.png"
	  alt									= "Pierre Morsa"
	
	# Pagination buttons
	[params.nav]
		previous						= "Plus récents" 
		next 								= "Plus anciens"

	# Aside infos, with section id (mandatory), text and button (optional)
	# Order elements as you want them to see in the sidebar
	# Special sections:
	# - links: id, text, no button
	# - rss: id, no text, button
	# - categories: id only
	# - copyright: id, text, no button
	[[params.aside]]
		id									= "blog"
		[params.aside.button]
			text							= "BLOG"
			link								= "/"
	[[params.aside]]
		id									= "howitisgoing"
		[params.aside.button]
			text							= "HOW IT IS GOING"
			link								= "/howitisgoing/"
	[[params.aside]]
		id									= "mac-automation"
		[params.aside.button]
			text							= "MAC AUTOMATION"
			link								= "/mac-automation/"
	[[params.aside]]
		id 									= "about"
		[params.aside.button]
			text							= "À PROPOS"
			link								= "/about/"
	[[params.aside]]
		id									= "links"
		text								= "Les sites que je soutiens"
		# No button, use /data/links files for links
	[[params.aside]]
		id									= "rss"
		[params.aside.button]
			text							= "S'abonner au fil RSS"
			link								= ""
	[[params.aside]]
		id 									= "contact"
		[params.aside.button]
			text							= "CONTACT"
			link								= "mailto:pier%72e.%6Dors%61@pm.me"
		
	[[params.aside]]
		id									= "categories"
	[[params.aside]]
		id									= "companies"
	[[params.aside]]
		id									= "promised"
	[[params.aside]]
		id									= "deadline"
	[[params.aside]]
		id									= "copyright"
		text								= "Site garanti sans cookies et sans JavaScript. Le contenu est en copie libre : vous pouvez tout copier et réutiliser librement."

# Related content links at bottom of articles
[related]
	threshold 							= 100
	includeNewer 					= true
	toLower 							= true
	[related.indices]
		name 								= "categories"
	  weight 							= 100
	  