baseurl					= "https://www.pierremorsa.com/"
defaultContentLanguage	= "fr"
language					= "fr"
languageCode				= "fr"
languageName				= "Français"
title					= "Pierre Morsa | Présenter en public et GTD"
theme					= "hugo-future-imperfect"
preserveTaxonomyNames	= false
paginate				= 5

[params]

    # Sets the meta tag description, usually reserved for the main page
    description			= "Le blog de Pierre Morsa, co-fondateur et Creative Cat d'Ideas on Stage, agence spécialisée dans les présentations en public."
    viewMorePostLink	= "/blog/"
    aboutlink			= "/about/"
    contactlink			= "/bookme/"

	# Aside elements
	[params.aside]
		[params.aside.about]
	    	text  		= "Pierre Morsa est co-fondateur et Creative Cat chez <a href='https://www.pierremorsa.com/ideas-on-stage/'>Ideas on Stage</a>, une agence de création de présentations, formation et coaching à la prise de parole et événements d'entreprise."
	    	button		= "En savoir plus"
		[params.aside.contact]	    	
			text		= "Pour me contacter écrivez-moi à <br><a href='m&#97;ilt&#111;&#58;&#112;i&#101;r%&#55;&#50;e&#46;%6D&#111;&#114;&#115;%61&#64;p&#109;&#46;m&#101;'>pierre&#46;morsa&#64;&#112;m&#46;m&#101;</a>."
		[params.aside.copyright]
			text		= "Site garanti sans cookies et sans JavaScript. Le contenu est en copie libre : vous pouvez tout copier et réutiliser librement. "

	# Parameters for little round pic on top of site
	[params.avatar]
	    src       			= "/pictures/main/pierre-morsa-avatar.png"
	    alt					= "Pierre Morsa"
	
		
	# Localization of text strings
	[params.localized.button]
		previous			= "Page précédente" 
		next 				= "Page suivante"
		rss					= "S'abonner au fil RSS"
	