[context.master]
  command = "hugo"
  
[context.production]
  command = "hugo"
    
[context.deploy-preview]
  command = "hugo"

# Used to test future versions of the blog    
[context.future]
  command = "hugo --buildFuture"
