[context.production.environment]
  command = "hugo"
    
[context.deploy-preview.environment]
  command = "hugo"

# Used to test future versions of the blog    
[context.future]
  command = "hugo --buildFuture"
