[context.production.environment]
  HUGO_VERSION = "0.53"
  command = "hugo"
    
[context.deploy-preview.environment]
  HUGO_VERSION = "0.53"
  command = "hugo --buildFuture"

# Used to test future versions of the blog    
[context.future]
  HUGO_VERSION = "0.53"
  command = "hugo --buildFuture"
