backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

publish_mode: editorial_workflow

media_folder: "static/pictures/uploads" # Media files will be stored in this repo
public_folder: "/pictures/uploads" # The src attribute for uploaded media will begin with /images/uploads